name: Parallelization Test
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Linting..."
      - run: sleep 10
  unit-tests:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - run: echo "Running unit tests..."
      - run: sleep 10
